# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        default: Weekly
        type: choice
        options:
          - Weekly
          - Hotfix

jobs:
  build_embed_app:
    name: embed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: abc; # fail

  build_prod_ios:
    name: iOS
    runs-on: macos-12
    needs: build_embed_app
    if: ${{ github.event.inputs.releaseType == 'Weekly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "Hello World"


  build_prod_android:
    needs: build_embed_app
    name: Android
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.releaseType == 'Weekly' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "Hello World"

  build_js_codepush:
    needs: build_embed_app
    name: Codepush
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.releaseType == 'Hotfix' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "Hello World"

  post_build:
    if: ${{ always() }} # Run even if previous steps was skipped
    needs: [build_prod_android, build_prod_ios, build_js_codepush]
    name: Post Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
